version: '3'

includes:

tasks:
    default:
        desc: Help
        summary: Show available tasks
        aliases:
            - help
        cmd: task --list-all

    install:
        desc: Install dependencies
        summary: Install Python dependencies
        cmd: pip install -r requirements.txt

    start:local:
        desc: Run locally
        summary: Run the functions locally (requires azure-functions-core-tools)
        cmd: func start
        preconditions:
            - func --version
